services:
  vllm:
    container_name: vllm
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VLLM_USE_MODELSCOPE=False
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ./storage-models/hf-hub/Qwen2.5-Coder-7B-Instruct-AWQ:/model
    ports:
      - "8000:8000"
    command: >
      /model
      --quantization awq
      --max-model-len 16384
      --gpu-memory-utilization 0.85
      --served-model-name coder-model
      --enable-prefix-caching
    networks:
      - ai-net
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:v0.8.9
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=vllm-coding-agent
      - LOG_LEVEL=debug
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8080:8080"
    depends_on:
      vllm:
        condition: service_started
    networks:
      - ai-net
    restart: unless-stopped

volumes:
  open-webui:

networks:
  ai-net:
    driver: bridge
