services:
  tika:
    image: apache/tika:3.2.3.0-full
    container_name: tika
    restart: unless-stopped
    networks:
      - ai-bridge
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8081:8080"                  # Host port 8081 → container 8080
    #volumes:
    #  - ./searxng/config:/etc/searxng
    #  - ./searxng/data:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8081/   # Change if using a domain/reverse proxy
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    networks:
      - ai-bridge
    depends_on:
      - tika

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:dev-ollama
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_GPU_OVERHEAD=0
      - OLLAMA_NUM_GPU=999
      - OLLAMA_NUM_CTX=131072
      - CONTENT_EXTRACT_ENGINE_TYPE=tika
      - TIKA_SERVER_URL=http://tika:9998
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    volumes:
      - open-webui:/app/backend/data
      - ollama:/root/.ollama
    ports:
      - "8080:8080"
      - "11434:11434"
    depends_on:
      - tika
      - searxng
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-bridge
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    shm_size: '64g'
    restart: unless-stopped

volumes:
  open-webui:
  ollama:
  searxng-config:
  searxng-data:

networks:
  ai-bridge:
    driver: bridge
